# Site settings
title: Jasm Sison's portfolio
description: A portfolio document
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jasm Sison
user_description: I am a mobile developer for Android and iOS.
user_title: Mobile Developer
email: jasm.sison@gmail.com
twitter_username: jasmsison
github_username: buggaboo
gplus_username: jasmsison

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
